config/routes.rb
Rails.application.routes.draw do
  get 'pages/index'
  resources :students
  resources :exams
  resources :teachers
  resources :reports
  resources :payments
  resources :pockets
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/exam.rb
class Exam < ApplicationRecord
end

app/models/payment.rb
class Payment < ApplicationRecord
end

app/models/pocket.rb
class Pocket < ApplicationRecord
end

app/models/report.rb
class Report < ApplicationRecord
end

app/models/student.rb
class Student < ApplicationRecord
end

app/models/teacher.rb
class Teacher < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/exams_controller.rb
class ExamsController < ApplicationController

    #untuk menampilkan form data baru
    def new 
     @exam = Exam.new
   end
 
   # untuk memproses data baru yang di masukan di form new
   def create      
     exam = Exam.new(resources_params)
     exam.save
     flash[:notice] = "exam #{exam.title} Berhasil di Tambah."
     redirect_to exams_path
   end
 
   #menampilkan data yang sudah disimpan di edit
   def edit
     id = params[:id]
     @exam = Exam.find id  
   end
 
   #melakukan proses ketika user mengedit data
   def update
     id = params[:id]
     @exam = Exam.find(id)
     @exam.update(resources_params) 
     flash[:notice] = "exam #{@exam.title} Berhasil di edit."  
     redirect_to exam_path(@exam)
   end
 
   #menghapus data
   def destroy
     id = params[:id]
     @exam = Exam.find(id)
     @exam.destroy
     flash[:notice] = "Buku #{@exam.title} Berhasil di Hapus."
     redirect_to exams_path
   end
 
   #menampilkan seluruh data yang ada di database
   def index
     @exams = Exam.all    
   end
 
   #menampilkan sebuah data secara detail
   def show
     id = params[:id]
     @exam = Exam.find id  
   end
 
   private #hanya bisa dipanggil dalam satu class
   def resources_params
     params.require(:exam).permit(:title, :mapel, :duration, :status, :level, :student_id)
   end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  def new
  end

  def index
  end

  def edit
  end

  def show
  end
end

app/controllers/pockets_controller.rb
class PocketsController < ApplicationController
  def new
  end

  def index
  end

  def edit
  end

  def show
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  def new
  end

  def index
  end

  def edit
  end

  def show
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  #untuk menampilkan form data baru
  def new 
    @student = Student.new
  end

  # untuk memproses data baru yang di masukan di form new
  def create      
    student = Student.new(resources_params)
    student.save
    flash[:notice] = "Student #{student.name} Berhasil di Tambah."
    redirect_to students_path
  end

  #menampilkan data yang sudah disimpan di edit
  def edit
    id = params[:id]
    @student = Student.find id  
  end

  #melakukan proses ketika user mengedit data
  def update
    id = params[:id]
    @student = Student.find(id)
    @student.update(resources_params) 
    flash[:notice] = "Student #{@student.name} Berhasil di edit."  
    redirect_to student_path(@student)
  end

  #menghapus data
  def destroy
    id = params[:id]
    @student = Student.find(id)
    @student.destroy
    flash[:notice] = "Buku #{@student.name} Berhasil di Hapus."
    redirect_to students_path
  end

  #menampilkan seluruh data yang ada di database
  def index
    @students = Student.all    
  end

  #menampilkan sebuah data secara detail
  def show
    id = params[:id]
    @student = Student.find id  
  end

  private #hanya bisa dipanggil dalam satu class
  def resources_params
    params.require(:student).permit(:name, :username, :age, :kelas, :address, :city, :nik)
  end
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
   #untuk menampilkan form data baru
   def new 
    @teacher = Teacher.new
  end

  # untuk memproses data baru yang di masukan di form new
  def create      
    teacher = Teacher.new(resources_params)
    teacher.save
    flash[:notice] = "Teacher #{teacher.name} Berhasil di Tambah."
    redirect_to teachers_path
  end

  #menampilkan data yang sudah disimpan di edit
  def edit
    id = params[:id]
    @teacher = Teacher.find id  
  end

  #melakukan proses ketika user mengedit data
  def update
    id = params[:id]
    @teacher = Teacher.find(id)
    @teacher.update(resources_params) 
    flash[:notice] = "Teacher #{@teacher.name} Berhasil di edit."  
    redirect_to teacher_path(@teacher)
  end

  #menghapus data
  def destroy
    id = params[:id]
    @teacher = Teacher.find(id)
    @teacher.destroy
    flash[:notice] = "Buku #{@teacher.name} Berhasil di Hapus."
    redirect_to teachers_path
  end

  #menampilkan seluruh data yang ada di database
  def index
    @teachers = Teacher.all    
  end

  #menampilkan sebuah data secara detail
  def show
    id = params[:id]
    @teacher = Teacher.find id  
  end

  private #hanya bisa dipanggil dalam satu class
  def resources_params
    params.require(:teacher).permit(:nik, :name, :age, :kelas, :mapel)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/exams_helper.rb
module ExamsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/pockets_helper.rb
module PocketsHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/exams/edit.html.erb
<%= link_to '<-- Back', exams_path %>
</br>
<%= form_for(@exam) do |f| %>
    <%= f.label :title %> </br>
    <%= f.text_field :title %> </br>   
    <%= f.label :mapel %> </br>
    <%= f.text_field :mapel %> </br>    
    <%= f.label :duration %> </br>
    <%= f.text_field :duration %> </br>
    <%= f.label :nilai %> </br>
    <%= f.text_field :nilai %> </br>     
    <%= f.label :status %> </br>
    <%= f.text_field :status %> </br>   
    <%= f.label :level %> </br>
    <%= f.text_field :level %> </br> 
    <%= f.label :student_id %> </br>
    <%= f.text_field :student_id %> </br>      
    </br>



    <%= f.submit "Save" %>
<% end %>

app/views/exams/index.html.erb
<% if flash[:notice].present? %>
    <%= flash[:notice] %>
    </br>
<% end %>
<%= link_to 'New exam', new_exam_path %>

</br>
</br>
<table>
    <tr>
        <td>Title</td>
        <td>Mapel</td>       
        <td>Duration</td>
        <td>Nilai</td>   
        <td>Status</td>
        <td>Level</td>
        <td>Student ID</td>
    </tr>
    <% @exams.each do |exam| %>
        <tr>           
            <td><%= exam.title %></td>            
            <td> <%= exam.mapel %></td>
            <td> <%= exam.duration %></td>      
            <td> <%= exam.nilai %></td>   
            <td> <%= exam.status %></td> 
            <td> <%= exam.level %></td> 
            <td> <%= exam.student_id %></td>       
            <td> <%= link_to 'Detail', exam_path(exam) %> | <%= link_to 'Edit', edit_exam_path(exam) %></td> 
            <td> <%= link_to 'Delete', exam_path(exam) , method: :delete, data: {confirm: 'Are you sure?'} %> </td>
        </tr>    
    <% end %>
</table>

app/views/exams/new.html.erb
<%= link_to '<-- Back', exams_path %>
</br>
<%= form_for(@exam) do |f| %>
    <%= f.label :title %> </br>
    <%= f.text_field :title %> </br>   
    <%= f.label :mapel %> </br>
    <%= f.text_field :mapel %> </br>    
    <%= f.label :duration %> </br>
    <%= f.text_field :duration %> </br>
    <%= f.label :nilai %> </br>
    <%= f.text_field :nilai %> </br>     
    <%= f.label :status %> </br>
    <%= f.text_field :status %> </br>   
    <%= f.label :level %> </br>
    <%= f.text_field :level %> </br> 
    <%= f.label :student_id %> </br>
    <%= f.text_field :student_id %> </br>      
    </br>



    <%= f.submit "Save" %>
<% end %>

app/views/exams/show.html.erb
<%= link_to '<-- Back', exams_path %>
</br>
Title:   <%= @exam.title %> </br>
Mapel   :   <%= @exam.mapel %> </br>
Duration   :   <%= @exam.duration %>  </br>
Nilai :   <%= @exam.nilai %> </br>
Status :   <%= @exam.status %> </br>
Level :   <%= @exam.level %> </br>
Student ID :   <%= @exam.student_id %> </br>

<% if flash[:notice].present? %>
    <%= flash[:notice] %>
<% end %>

app/views/payments/edit.html.erb
<h1>Payments#edit</h1>
<p>Find me in app/views/payments/edit.html.erb</p>

app/views/payments/index.html.erb
<h1>Payments#index</h1>
<p>Find me in app/views/payments/index.html.erb</p>

app/views/payments/new.html.erb
<h1>Payments#new</h1>
<p>Find me in app/views/payments/new.html.erb</p>

app/views/payments/show.html.erb
<h1>Payments#show</h1>
<p>Find me in app/views/payments/show.html.erb</p>

app/views/pockets/edit.html.erb
<h1>Pockets#edit</h1>
<p>Find me in app/views/pockets/edit.html.erb</p>

app/views/pockets/index.html.erb
<h1>Pockets#index</h1>
<p>Find me in app/views/pockets/index.html.erb</p>

app/views/pockets/new.html.erb
<h1>Pockets#new</h1>
<p>Find me in app/views/pockets/new.html.erb</p>

app/views/pockets/show.html.erb
<h1>Pockets#show</h1>
<p>Find me in app/views/pockets/show.html.erb</p>

app/views/reports/edit.html.erb
<h1>Reports#edit</h1>
<p>Find me in app/views/reports/edit.html.erb</p>

app/views/reports/index.html.erb
<h1>Reports#index</h1>
<p>Find me in app/views/reports/index.html.erb</p>

app/views/reports/new.html.erb
<h1>Reports#new</h1>
<p>Find me in app/views/reports/new.html.erb</p>

app/views/reports/show.html.erb
<h1>Reports#show</h1>
<p>Find me in app/views/reports/show.html.erb</p>

app/views/students/edit.html.erb
<%= link_to '<-- Back', students_path %>
</br>
<%= form_for(@student) do |f| %>
    <%= f.label :name %> </br>
    <%= f.text_field :name %> </br>
    <%= f.label :username %> </br>
    <%= f.text_field :username %> </br>    
    <%= f.label :age %> </br>
    <%= f.text_field :age %> </br>
    <%= f.label :kelas %> </br>
    <%= f.text_field :kelas %> </br>     
    <%= f.label :address %> </br>
    <%= f.text_field :address %> </br>     
    <%= f.label :city %> </br>
    <%= f.text_field :city %> </br>     
    <%= f.label :nik %> </br>
    <%= f.text_field :nik %> </br>          

    </br>



    <%= f.submit "Save" %>
<% end %>

app/views/students/index.html.erb
<% if flash[:notice].present? %>
    <%= flash[:notice] %>
    </br>
<% end %>

<%= link_to 'New student', new_student_path %>

</br>
</br>
<table>
    <tr>
        <td>Student ID</td>
        <td>Name</td>
        <td>Username</td>
        <td>Age</td>
        <td>Class</td>
        <td>Address</td>
        <td>City</td>
        <td>NIK</td>
    </tr>
    <% @students.each do |student| %>
        <tr>
            <td><%= link_to "#{student.id}", student_path(student) %></td>
            <td><%= student.name %></td>
            <td> <%= student.username %></td>
            <td> <%= student.age %></td>
            <td> <%= student.kelas %></td>
            <td> <%= student.address %></td>
            <td> <%= student.city %></td>
            <td> <%= student.nik %></td>
            <td> <%= link_to 'Detail', student_path(student) %> | <%= link_to 'Edit', edit_student_path(student) %></td> 
            <td> <%= link_to 'Delete', student_path(student) , method: :delete, data: {confirm: 'Are you sure?'} %> </td>
        </tr>    
    <% end %>
</table>

app/views/students/new.html.erb
<%= link_to '<-- Back', students_path %>
</br>
<%= form_for(@student) do |f| %>
    <%= f.label :name %> </br>
    <%= f.text_field :name %> </br>
    <%= f.label :username %> </br>
    <%= f.text_field :username %> </br>    
    <%= f.label :age %> </br>
    <%= f.text_field :age %> </br>
    <%= f.label :kelas %> </br>
    <%= f.text_field :kelas %> </br>     
    <%= f.label :address %> </br>
    <%= f.text_field :address %> </br>     
    <%= f.label :city %> </br>
    <%= f.text_field :city %> </br>     
    <%= f.label :nik %> </br>
    <%= f.text_field :nik %> </br>          

    </br>



    <%= f.submit "Save" %>
<% end %>

app/views/students/show.html.erb
<%= link_to '<-- Back', students_path %>
</br>
Name   :   <%= @student.name %> </br>
Username   :   <%= @student.username %> </br>
Age   :   <%= @student.age %>  </br>
Kelas :   <%= @student.kelas %> </br>
Address :   <%= @student.address %> </br>
City :   <%= @student.city %> </br>
Nik :   <%= @student.nik %> </br>

<% if flash[:notice].present? %>
    <%= flash[:notice] %>
<% end %>

app/views/teachers/edit.html.erb
<%= link_to '<-- Back', teachers_path %>
</br>
<%= form_for(@teacher) do |f| %>
    <%= f.label :nik %> </br>
    <%= f.text_field :nik %> </br>   
    <%= f.label :name %> </br>
    <%= f.text_field :name %> </br>    
    <%= f.label :age %> </br>
    <%= f.text_field :age %> </br>
    <%= f.label :kelas %> </br>
    <%= f.text_field :kelas %> </br>     
    <%= f.label :mapel %> </br>
    <%= f.text_field :mapel %> </br>        
    </br>



    <%= f.submit "Save" %>
<% end %>

app/views/teachers/index.html.erb
<% if flash[:notice].present? %>
    <%= flash[:notice] %>
    </br>
<% end %>
<%= link_to 'New teacher', new_teacher_path %>

</br>
</br>
<table>
    <tr>
        <td>Nik</td>
        <td>Name</td>       
        <td>Age</td>
        <td>Class</td>   
        <td>Mapel</td>
    </tr>
    <% @teachers.each do |teacher| %>
        <tr>
            <td><%= link_to "#{teacher.nik}", teacher_path(teacher) %></td>
            <td><%= teacher.name %></td>            
            <td> <%= teacher.age %></td>
            <td> <%= teacher.kelas %></td>      
            <td> <%= teacher.mapel %></td>         
            <td> <%= link_to 'Detail', teacher_path(teacher) %> | <%= link_to 'Edit', edit_teacher_path(teacher) %></td> 
            <td> <%= link_to 'Delete', teacher_path(teacher) , method: :delete, data: {confirm: 'Are you sure?'} %> </td>
        </tr>    
    <% end %>
</table>

app/views/teachers/new.html.erb
<%= link_to '<-- Back', teachers_path %>
</br>
<%= form_for(@teacher) do |f| %>
    <%= f.label :nik %> </br>
    <%= f.text_field :nik %> </br>   
    <%= f.label :name %> </br>
    <%= f.text_field :name %> </br>    
    <%= f.label :age %> </br>
    <%= f.text_field :age %> </br>
    <%= f.label :kelas %> </br>
    <%= f.text_field :kelas %> </br>     
    <%= f.label :mapel %> </br>
    <%= f.text_field :mapel %> </br>        
    </br>



    <%= f.submit "Save" %>
<% end %>

app/views/teachers/show.html.erb
<%= link_to '<-- Back', teachers_path %>
</br>
NIK :   <%= @teacher.nik %> </br>
Name   :   <%= @teacher.name %> </br>
Age   :   <%= @teacher.age %>  </br>
Kelas :   <%= @teacher.kelas %> </br>
Mapel :   <%= @teacher.mapel %> </br>

<% if flash[:notice].present? %>
    <%= flash[:notice] %>
<% end %>